trigger:
  - main

pool: default

steps:
  # template: template.yml
  # parameters:
  #   envs: [ "OA", "ProgressivelL", "USAA", "yyy", "nir"]
  #   branches: [ "Main", "Release"]
  #   tenant: [ "BOLT"]
  - script: echo HELLO